sudo: required # we need super user permissions anytime we make use of Docker

services:
  - docker # 1. Tell Travis we need a copy of docker running

before_install:
  - docker build -t erant10/docker-react -f Dockerfile.dev . # 2. Build our image using Dockerfile.dev

script:
  - docker run erant10/docker-react npm run test -- --coverage # 3. Tell Travis how to run our test suite

#4. Tell Travis how to deploy our code to AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-381207684223"
  bucket_path: "docker-react"
  on:
    branch: master # only deploy when master branch is modified
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"